# Generated by Django 3.0.7 on 2020-06-26 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200626_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
