# Generated by Django 3.0.8 on 2020-07-02 10:05

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0004_blogpost_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=django_quill.fields.QuillField(default='', null=True),
        ),
    ]
