# Generated by Django 3.0.8 on 2020-07-08 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='products',
            new_name='blogs',
        ),
    ]
